### ISSUE TITLE
Problems with environment export (Missing files, weird normal shading) in new versions of Flagrum.

### ISSUE THREAD

**Issue by Larxian** [Kizari/Flagrum-Blender#3]
Hello.

I noticed that there is an issue with the environment export tool in the recent versions of Flagrum. 
The environment export feature was gone for a few weeks / month because of a bug, and since it's been added back, it has issues that were not there before. 

When exporting / importing an environment into Blender, there are now a lot of missing models, and the normals look very strange, almost like cell shading? 

As example, when exporting "area_ravettrice", the export done with Flagrum **v1.5.5** is only **11.2 gb**, while the export done with **v1.4.11** (the last version I have that still exports fine for me) is **18.4 gb**.

Here are some screenshots showing the differences.
v1.4.11:
![v1 4](https://github.com/Kizari/Flagrum-Blender/assets/14320479/2edcde2e-320c-4ab3-bad4-9f03b44d63a4)
v1.5.5:
![v1 5](https://github.com/Kizari/Flagrum-Blender/assets/14320479/2c2863b8-82df-4cc3-9b6d-6cb18a4d9200)
v1.4.11:
![v1 4_2](https://github.com/Kizari/Flagrum-Blender/assets/14320479/f2414b0c-6e99-412d-a6cd-65d212af0a0e)
v1.5.5:
![v1 5_2](https://github.com/Kizari/Flagrum-Blender/assets/14320479/13d11719-2e69-4a0b-beec-d4cc245aefbe)

I think that's all the informations I could report on that, but if you need anything else let me know. I thought this was worth reporting because it seems like a major issue, unless it's just me being affected? Not sure. For the moment I'm using the older version offline (to keep it from updating) because it's what works the best for me.

**Comment by Larxian** [comment]
The version of Blender I'm using is 3.4.1, which is importing assets exported from Flagrum 1.4.11 fine.
I just tried with Blender 3.0 to verify if there was any difference, the shading issue is the same :
![3 0](https://github.com/Kizari/Flagrum-Blender/assets/14320479/5ab43973-3d8d-4659-89ed-de6c0e9d55e3)

It's also not just a problem on Blender's side since like I mentionned the scene exported from the current version of Flagrum is smaller in size.
Surprisngly, the amount of files exported is actually the same, but the size of the files are different, here's a quick example:

Files exported from v1.4 (working correctly):
![files 1 4](https://github.com/Kizari/Flagrum-Blender/assets/14320479/7895e544-f16f-47f1-959e-f3e6c68f6192)

Files exported from v1.5 (missing objects in blender and weird shading):
![files 1 5](https://github.com/Kizari/Flagrum-Blender/assets/14320479/77d3e2f3-e7ba-4885-a4c2-d6953e883323)

**Comment by Larxian** [comment]
Hey, so I tried exporting Galdin to give you a point of comparison. I never exported it before so I'm not sure if anything is missing, doesn't seem like it, unless it's supposed to have some terrain in it.
![Sans titre](https://github.com/Kizari/Flagrum-Blender/assets/14320479/d74a03a5-ecd8-4fb1-b683-79643bfc4f70)
It came out at 1,47gb, 2455 objects in the scene.

As for area_revattrice, like I mentionned in my original post, the export folder is indeed much smaller, 11,2 GB instead of 18,4 GB for the correct version. 
The models folder is almost the same size, there is a small difference, but curiously the broken export is actually the heavier one. 2,44 GB for the broken export, 2,42 GB for the correct export.
The biggest size difference is with the texture folders, the one from the faulty export (from Flagrum 1.5.5) is 8.76 GB, while the texture folder from the correct export is 16 GB, almost twice the size.

Could it be that there is a problem with the material export and Blender skips the objects with missing textures during the import?

**Comment by Larxian** [comment]
Okay so I exported a few scenes from both versions of flagrum, here are the results: 
"map_ravettrice_altissia_a" doesn't show any difference in the amount of objects, only shader issue.
1.4:
![A 1 4](https://github.com/Kizari/Flagrum-Blender/assets/14320479/78ca0471-a83f-4791-b859-0c5f50320d66)
1.5:
![A 1 5](https://github.com/Kizari/Flagrum-Blender/assets/14320479/91e7d0b0-de11-47ad-85f0-7912e11a68ae)

From there I was afraid how many scenes I would have to test to see the issue happen, but "thankfully", "**map_ravettrice_altissia_b**" is where issues start.

1.4:
![B 1 4](https://github.com/Kizari/Flagrum-Blender/assets/14320479/6568a3b1-07ae-4756-b27a-5a9740064235)
1.5:
![B 1 5](https://github.com/Kizari/Flagrum-Blender/assets/14320479/1400cf88-2f16-4a19-b18e-89759b3da49e)

The whole map isn't needed to find missing objects, and maybe the fact that the first map doesn't have any missing stuff but the second does can somehow help too? I don't know, but I hope this will help you!

**Comment by Kizari** [comment]
Ahh, thanks for that. Had already started doing the whole thing, and it did indeed throw an error. Good to know I can focus on a single sector though when I have to retest after attempting to fix things.

I am curious, do you get a bunch of "Failed to load" errors when you import the 1.4.X export into Blender? You can go to `Window > Toggle System Console` to see this.

![image](https://github.com/Kizari/Flagrum-Blender/assets/25322543/96a14c15-9b9c-4b05-a7ae-9f3fd9b0b092)

Everything starting from "TypeError" is the error that causes the import to fail and is why there is a bunch of stuff missing. You wouldn't see this on the 1.4.X export, so only interested to know if the "Failed to load" errors present there, as it may also be a cause of missing models if not.

This error should help me solve the problem though, it seems the UV data of one or more models is corrupted in the 1.5.X export.

**Comment by Larxian** [comment]
I don't have any TypeError, however I do have the "Failed to load data" on a few things.
![error1](https://github.com/Kizari/Flagrum-Blender/assets/14320479/765f1c1f-409d-445b-ae17-26465e0abad8)

**Comment by Kizari** [comment]
There we go. Picture taken from a Flagrum 1.5.6 (development version) export of map_ravettrice_altissia_b. Matches your 1.4.X export perfectly from what I can see. Will release this with the rest of 1.5.6 as soon as it's done, shouldn't be far away.

![image](https://github.com/Kizari/Flagrum-Blender/assets/25322543/b8cbe2c0-07b5-4a58-8e30-8d28684ecd42)
